# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 뜻이 있는 곳에 !!!!! 길이 있다
subtitle: <나를 위한 기록 노트>
author: 옐란
language: ko
timezone: Asia/Seoul

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://github.com/jukyellow/jukyellow.github.io       # Note: don't forget to modify the CNAME file to your url
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

#Custom Setting Start

# Site settings
SEOTitle: 옐란
email: jukyellow@gmail.com
description: "yelan`s tech blog"
keyword: "AI, Data Science, MSA"
header-img: img/header_img/home-bg-beautiful-shot-cars-road-blue-sky.jpg
signature: true #show signature
signature-img: img/signature/


# SNS settings
# RSS: false
# weibo_username:     Demonbaneen
# zhihu_username:     Demonbane
github_username:    jukyellow
# twitter_username:   Demonbane_x
#facebook_username:  jukyellow
#linkedin_username:
#medium_username : https://yelran.medium.com/

# Build settings
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`


# Disqus settings
disqus_username: yelran-s-tech-blog #jukyellow.github.io


# Duoshuo settings
# duoshuo_username: kaijun
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing


# Analytics settings
# Baidu Analytics
# ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
ga_track_id: G-EG1ZFE1SGM        # Format: UA-xxxxxx-xx
ga_domain: https://jukyellow.github.io/


# (21.02.01)hexo-3.9 -> 5.3.0 init + theme add -> set themes\beantech\_config.yml
# # Sidebar settings
sidebar: true   # whether or not using Sidebar.
sidebar-about-description: "Where there's a will, there's a way!"
sidebar-avatar: img/aboutMe.JPG      # use absolute URL, seeing it's used in both `/` and `/about/`
#widgets:
#- short-about
#- recent-posts
#- archive
#- category
# #- friends-blog
# #- featured-tags


# widget behavior
## Archive
archive_type: 'monthly'
show_count: true

## Categories(juk add)
category_show_count: true
# 0 displays all categories and child categories
category_depth : 0

## Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


## Friends
#friends: [
#    {
#        title: "Bean Tech",
#        href: "http://beantech.org"
#    }
#    ,{
#        title: "Kaijun's Blog",
#        href: "http://blog.kaijun.rocks"
#    },{
#        title: "Hux Blog",
#        href: "http://huangxuan.me"
#    },{
#        title: "It Helps SEO",
#        href: "#"
#    }
#]


#Custom Setting End



# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: true # Transform title into titlecase
#external_link: true # Open external links in new tab
external_link: # Open external links in new tab
  enable: true
filename_case: 1
render_drafts: true
post_asset_folder: true
relative_link: true
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: false

# Category & Tag
default_category: uncategorized
category_map: true
tag_map: true
home_posts_tag: true # show posts tags

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: archives

archive_generator:
  per_page: 10
  yearly: true
  monthly: true
  daily: false

# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: beantech

#sitemap
sitemap:
  path: sitemap.xml

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: https://github.com/jukyellow/jukyellow.github.io
  branch:
